### ISSUE TITLE
What about $templateCache?

### ISSUE THREAD

**Issue by ClementParis016** [toddmotto/angular-styleguide#100]
Since we are writing component's HTML in their respective JS definition file, is there any way we could still make use of [Angular's $templateCache](https://docs.angularjs.org/api/ng/service/$templateCache)?
Or is it something that is no more a good practice in 1.5.x and that should be avoided?

**Comment by toddmotto** [comment]
$templateCache is still a great tool to use. I'll add it to the list :)
