### ISSUE TITLE
should I use $log or console.log on angular 1.x ES6?

### ISSUE THREAD

**Issue by sibelius** [toddmotto/angular-styleguide#102]
should I use $log or console.log on angular 1.x ES6?

**Comment by floriangosse** [comment]
I think this has nothing to do with the syntax 

I think the logger which is build in has some advantages over the normal logger. E.g. if you print debug messages you can disable these messages for your production build.

**Comment by sibelius** [comment]
@floriangosse do u have an example of injecting $log

should I do something like this:

```js
class TodoController {
  constructor($log) {
    this.$log = $log;
  }
}
```

it just feel weird to use this.$log.debug, instead of just $log.debug

**Comment by toddmotto** [comment]
I've never really used `$log`.

Binding `this.foo = foo;` inside the constructor is binding a dependency to the instance of the class, therefore you need to do it. This is the same with pretty much everything using classes (React/Angular 1/2)

**Comment by floriangosse** [comment]
Or you could use a logger which is independent of angular like [simple-logger](https://www.npmjs.com/package/simple-logger). But most of the time I use `$log` or simply `console`.

**Comment by sibelius** [comment]
I feel that dependency injection of angular does not have much value if we r using `import from` syntax
