### ISSUE TITLE
Naming convention used in style guide

### ISSUE THREAD

**Issue by xylosper** [toddmotto/angular-styleguide#106]
I've read the excellent new style guide for angular 1.5 and ES6.
Onething I'm curious in is what's the naming convention which is used in the style guide.

As far as I can see from the style guide, I guess next things:

* camelCase for imported external module variable (`uiRouter`)
* PascalCase for imported internal module variable (`AppComponent`)
* dot-connected name (snake.case?) in module name (`'todo.form'`)
* camelCase for component name (`'todoForm'`)
* PascalCase for service name (`'TodoService'`)
* PascalCase for injected service variable (`TodoService`)

Is there any document which covers full convention for styleguide?

**Comment by blowsie** [comment]
- PascalCase for component variable (`TodoFormComponent`)

**Comment by blowsie** [comment]
Would be good if we can form a table like the one found here.
https://github.com/mgechev/angularjs-style-guide

On a side note, the great contacts app that has been added to this guide doesn't actually follow the guide very closely at all. That leaves some people, like me, somewhat confused.

**Comment by toddmotto** [comment]
@blowsie Which piece doesn't follow the styleguide? The app is ES5, and apart from controller assignment I can't see what else, `.controller()` in the app is to register with the angular core due to the lack of ES6 modules.

**Comment by blowsie** [comment]
To be fair a lot of the differences are around naming, and as you say, ES6.

To name a few, the sample app;

- Does not use an `index.js` file for each component
- Has a root component named `'root'` , the style guide uses `'app'`
- Has a module named `'components'`, where as the style guide uses `'app.components'`
 (use of some form of namespace)

If i remember any other or find any more differences I'll let you know.

None the less, both the guide, the courses and the app are excellent and I learnt a lot from them.

See you at angular connect!

**Comment by toddmotto** [comment]
Ah I see. Yes the root component allows the "app" component to be abstracted for authentication purposes. Similarly with ES6 we can import the directory name and export using index, just reduces the syntax a little. And module names are completely up to you - namespaced or not :) - my main focus here was allowing the developer to use the right architecture patterns etc. 

Thanks for the kind words on the style guide and course content! See you tomorrow!

@toddmotto
