### ISSUE TITLE
The way to pass reference to event through the route config

### ISSUE THREAD

**Issue by michalpanek** [toddmotto/angular-styleguide#110]
I have that situation: 

Route config from statefull route component:

```javascript
.state('conferences.conferencesList', {
        url: '/list',
        component: 'conferenceList',
        params: {
          conferencesList: undefined,
          onAddConference: undefined
        },
        resolve: {
          conferencesList: ($stateParams) => $stateParams.conferencesList,
          onAddConference: ($stateParams) => $stateParams.onAddConference
        }
```

and I have stateless component, which is children component for statefull component:

```javascript
let conferenceListComponent = {
  bindings: {
    conferencesList: '<',
    onAddConference: '&'
  },
  template,
  controller
};
```

where **onAddConference** is a event to fire up to statefull parent component by stateless component (**conferenceList** in my example) 
How Can I pass to bindings of stateless component "reference" to function from my statefull component ? How can I do this in route configuration ? 

I tried send "reference" to function by 
```javascript
 $state.go('somestate', ({
someBindings: something,
someEvent: this.someFunction
}); 
```

but I got a error message:

> TypeError: Cannot read property '1' of null(…)

Is there a way to solve this issue, or am I entirely wrong ?

**Comment by michalpanek** [comment]
Thanks Todd for answered me in _Disqus_. 

The js _object_ must be passed through angular ui-router _params_ with bindings inside, because of that js not really supporting passing  [variables by references](http://stackoverflow.com/questions/7744611/pass-variables-by-reference-in-javascript), and when simple value, or function is passed by ui-router params, there is no possibility that bindings will be updated after changed in route component parent.

Please, correct me if I am wrong.

**Comment by toddmotto** [comment]
Hey @michalpanek did you fix this? Sorry slipped checking this one. If you're still having issues can you drop a jsfiddle of the code and reopen :)

**Comment by michalpanek** [comment]
Yea, already I found the solution: [https://github.com/angular-ui/ui-router/issues/2888#issuecomment-242850953](https://github.com/angular-ui/ui-router/issues/2888#issuecomment-242850953). but thanks:)
