### ISSUE TITLE
Naming conventions for services

### ISSUE THREAD

**Issue by kpudlik** [toddmotto/angular-styleguide#112]
As far as I know in Angular 2 instances are named by `camelCase`, e.g:

`private sampleService: SampleService`

Why are you naming service instances by `PascalCase`?

Something like this looks like calling a static method:
`SampleService.method()`
when it's actually a method of an instance

**Comment by toddmotto** [comment]
Gonna bake this into the next updates: 
```js
constructor(authService, $state) {
      'ngInject';
      this.authService = authService;
      this.$state = $state;
}
```
