### ISSUE TITLE
Using require vs bindings in components

### ISSUE THREAD

**Issue by alextsg** [toddmotto/angular-styleguide#119]
I noticed that in the components section, it states that the `require` object is for referencing inherited logic alongside `$onInit`. What's the recommendation for using `require` versus putting a function in the component's `bindings`? For example, should I be doing:

```
require : {
   parent: '^parent'
}
...
$ctrl.parent.doStuff();
```
or
```
bindings: {
    doStuff: '&'
}
...
$ctrl.doStuff()
```
Thanks! Sorry if this is the wrong place for this!

**Comment by toddmotto** [comment]
Good question indeed! If you can, use `bindings` as much as possible and think about stateless/stateful components. Using `require` kind of goes against the principles of pure components, and inheriting controllers isn't as easy to test, or as reliable IMO (due to DOM placement etc).

**Comment by alextsg** [comment]
Yeah makes a lot of sense. Thank you!

**Comment by toddmotto** [comment]
Anytime :)!

**Comment by Prasanna-Sridharan** [comment]
Hi @alextsg @toddmotto I guess using 'require' makes sense when you want to utilize a directive API (like a service) which is not a parent to the component. Also require supports multiple API's to be referred. To access parent scope, 'bindings' are helpful and minimal. Please correct me if am wrong.
