### ISSUE TITLE
Possible code mistake. Clarification needed.

### ISSUE THREAD

**Issue by adiman9** [toddmotto/angular-styleguide#120]
I think there is a mistake in the code snippet for the stateless component. I beleive the constructor needs `this.EventEmitter = EventEmitter` and then `this.EventEmitter({ todo: this.todo});` inside the onSubmit method.

I am pretty sure this is a mistake, if so, I can submit a PR. Just wanted clarification that this is in incorrect.

![selection_001](https://cloud.githubusercontent.com/assets/7476318/18294099/cfbabbce-748e-11e6-9b46-7677e0d58add.png)

**Comment by toddmotto** [comment]
Ah yes that's an error. Too much TypeScript. PR would be great (plz don't forget the i18n files - need a way to automate this still).

@toddmotto

**Comment by adiman9** [comment]
I have created the pull request. Included the i18n files too.
