### ISSUE TITLE
Suggestion of best practise

### ISSUE THREAD

**Issue by ptitgraig** [toddmotto/angular-styleguide#123]
Hello.
I suggest the following best practise regarding component:

> Avoid component attribute name starting with `data-` as AngularJS eats the "data-" string

```html
<!-- my-component.html -->
<my-component data-src="$ctrl.dataSrc"></my-component>
```

```js
// my-component.js
...
bindings : {
  dataSrc: '<'
}
```

This code does above not work because the binding should be:
```js
// my-component.js
...
bindings : {
  src: '<'
}
```

This is source of confusion. One should avoid attribute starting with `data-`

**Comment by AkosLukacs** [comment]
True, it's part of a documented normalization step for attribute names:
https://docs.angularjs.org/api/ng/type/$compile.directive.Attributes#!

**Comment by toddmotto** [comment]
I think this is just one of those things that you'd know if you were using `data-*` attributes, I don't feel it's styleguide worthy IMO.
