### ISSUE TITLE
Where are the third party angular library located in the folder structure

### ISSUE THREAD

**Issue by LukasChen** [toddmotto/angular-styleguide#131]
Where are the third party angular library located in the folder structure in this styleguide?

**Comment by noderat** [comment]
You'd usually find 3rd party libraries as dependencies listed in your package.json and thus in the node_modules directory.

**Comment by toddmotto** [comment]
Yeah, you can reference the 1.5 component based app (in the readme of this repo too) and dig through how it uses `node_modules` to compile/concat: https://github.com/toddmotto/angular-1-5-components-app/blob/master/gulpfile.babel.js#L28-L33

**Comment by LukasChen** [comment]
But what if the third party library is not listed in npm yet?

**Comment by floriangosse** [comment]
You should try to use dependencies via npm. If it is not possible you could add a folder `vendor/` next to `app/`.
