### ISSUE TITLE
Issues with httpInterceptor services

### ISSUE THREAD

**Issue by blowsie** [toddmotto/angular-styleguide#140]
Based on this article;
http://onehungrymind.com/winning-http-interceptors-angularjs/

I created the following code.

```
// services/api-interceptor.service.js
class ApiInterceptorService {
  constructor($q) {
    'ngInject';
    this.$q = $q;
  }

  responseError = function(response) {
    // Handle the error here, using a modal or event?
    console.error(response.config.method, response.config.url, 'failed');
    console.log(this.$q);     // undefined
    return this.$q.reject(response);
  }
}

export default ApiInterceptorService;
```

```
// services/services.js
import angular from 'angular';

import apiInterceptorService from './api-interceptor.service';

export default angular
  .module('app.services', [])
  .service({
    apiInterceptorService
  })
  .name
```

```
// app.js
import angular from 'angular';
import angularResource from 'angular-resource';
import uiRouter from 'angular-ui-router';

import '../libs/libs';

import Config from './app.settings.constant';
import Common from './common/common';
import Components from './components/components';
import AppServices from './services/services';
import AppComponent from './app.component';
import APP_SETTINGS from './app.settings.constant';

angular
  .module('app', [
    angularResource,
    uiRouter,
    Common,
    Components,
    AppServices
  ])
  .config(($locationProvider, $urlRouterProvider, $stateProvider, $httpProvider) => {
    'ngInject';
    $locationProvider.html5Mode(true).hashPrefix('!');
    $urlRouterProvider.otherwise('/');
    $httpProvider.interceptors.push('apiInterceptorService');
  })
  .component('app', AppComponent)
  .constant('APP_SETTINGS', APP_SETTINGS);

```

---

The problem I have is that assigning `this.$q` to the interceptor constructor does not work.
When the `responseError` function is executed `this.$q` is not available. 
![image](https://cloud.githubusercontent.com/assets/308572/20833031/68aeeb4a-b885-11e6-9e23-701104253ee2.png)

I assume this is because the `$httpProvider` is only taking the relevant functions from the service I have pushed via `$httpProvider.interceptors.push('apiInterceptorService');`

Any ideas how we can work around this?

FYI, i have almost the same code running in ES5 and its working just fine.

**Comment by xavhan** [comment]
```js
...
responseError(response) {
    // Handle the error here, using a modal or event?
    console.error(response.config.method, response.config.url, 'failed');
    console.log(this.$q);     // undefined
    return this.$q.reject(response);
  }
...
```
function keyword create a new context and the this value changed

**Comment by blowsie** [comment]
@xavhan oops, thank you.

However I still have the same issue.
![image](https://cloud.githubusercontent.com/assets/308572/20839028/dd81592c-b8a2-11e6-9014-6dfd10386497.png)

**Comment by mmiszy** [comment]
You have to bind `respondeError` method. You can either use the [`@autobind` decorator](https://github.com/andreypopp/autobind-decorator) or an arrow function:

```javascript
// services/api-interceptor.service.js
export default class ApiInterceptorService {
  constructor($q) {
    'ngInject';
    this.$q = $q;
  }

  responseError = response => {
    return this.$q.reject(response);
  }
}
```

**Comment by blowsie** [comment]
@mmiszy thanks, but how does this arrow function differ from my original sample?

```
responseError = response => {
    return this.$q.reject(response);
  }
```
vs
```
 responseError = function(response) {
    return this.$q.reject(response);
  }
```

**Comment by mmiszy** [comment]
@blowsie Arrow function `() => {}` has _lexical scope_ (_lexical this_) whereas `function () {}` does not.
In this context we could say that arrow function is equivalent to `function () {}.bind(this)`. In other words this:
```javascript
responseError = response => {
    return this.$q.reject(response);
};
```

is equivalent (in this context!) to this:

```javascript
responseError = function(response) {
    return this.$q.reject(response);
}.bind(this);
```

You can read more about arrow functions and _lexical this_ [in this article](https://www.sitepoint.com/es6-arrow-functions-new-fat-concise-syntax-javascript/).

**Comment by blowsie** [comment]
@mmiszy Thanks for the explanation!
