### ISSUE TITLE
Services vs. Factories

### ISSUE THREAD

**Issue by SirTophamHatt** [toddmotto/angular-styleguide#15]
"All Angular Services are singletons, using .service() or .factory() differs the way Objects are created."

It is correct that all Angular Services return singleton objects. The service gets the result of instantiating the constructor function passed. One adds properties to the singleton by referencing "this" in the constructor function.

Angular Factories, on the other hand, gets the returned value of the function, which may return singleton objects, primitive types, or functions. One can certainly "new" a Factory if the Factory function returns a function.

**Comment by toddmotto** [comment]
Closing off, the styleguide has just been completely rewritten in ES6 for Angular 1.5+ (component architecture/components/one-way dataflow etc).

**Comment by toddmotto** [comment]
Just a heads up that I wrote an article detailing differences between each a few months ago: https://toddmotto.com/factory-versus-service
