### ISSUE TITLE
Angular wrapper references ( link fn params wrong)...

### ISSUE THREAD

**Issue by Hotell** [toddmotto/angular-styleguide#23]
Hi Todd.

I think here is a typo, $document service should be  injected as parameter of the directive function right?
instead of this:
```js
// recommended
function dragUpload () {
  return {
    link: function ($scope, $element, $attrs, $document) {
      $document.addEventListener('click', function () {

      });
    }
  };
}
```

this:
```js
// recommended
function dragUpload ($document) {
  return {
    link: function ($scope, $element, $attrs) {
      $document.addEventListener('click', function () {

      });
    }
  };
}
```

also I think, that it's a good practice, not to prefix positional link function arguments with dollar sign, because those are not injected services via DI.

And last one: It's more readable, imho, to extract controller/link/compile function outside of the directive definition object like this:

```js


;(function () {
    angular.module('myApp', [])
        .directive('myDirective', myDirective);

    function myDirective( /* DI */ ) {

        return {
            restrict: 'EA',
            controller: Ctrl,
            controllerAs: 'ctrl',
            link: linkFn,
            template: '<div>My name is {{ ::ctrl.myName }}</div>'
        };

        function Ctrl($log) {
            // ...
            this.$log = $log;
            var vm = this;

            vm.myName = 'Martin';
        }

        Ctrl.prototype.sayHi = function () {
            this.$log(this.myName);
        }

        function linkFn(scope, element, attrs) {
            // ...
        }
    }
})();
```
What do you say?
thanks and btw you did a great job on writing this guide!

**Comment by toddmotto** [comment]
Thanks for the comments, but closing off, the styleguide has just been completely rewritten in ES6 for Angular 1.5+ (component architecture/components/one-way dataflow etc). :)
