### ISSUE TITLE
Routing resolves

### ISSUE THREAD

**Issue by ezraroi** [toddmotto/angular-styleguide#24]
Hi,
about the Routing resolves solution you suggest, it looks very good but there is a problem when the controller is not in the same file as the app.js.

How do you suggest to solve it?

**Comment by thedig** [comment]
having same resolve issue since my team/app is following papa's IIFE recommendation: https://github.com/johnpapa/angular-styleguide#iife
which conflicts with Todd's IIFE recommendation above

hadn't realized this disparity in the two guides until this specific issue

**Comment by toddmotto** [comment]
I don't see the benefit in having (for example) 1000 IIFEs in an Angular
app with 1000 files. I simply wrap each module at build time inside an IIFE.

On 1 December 2015 at 22:07, Dig Vargas <notifications@github.com> wrote:

> having same resolve issue since my team/app is following papa's IIFE
> recommendation: https://github.com/johnpapa/angular-styleguide#iife
> which conflicts with Todd's IIFE recommendation above
>
> hadn't realized this disparity in the two guides until this specific issue
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/toddmotto/angularjs-styleguide/issues/24#issuecomment-161110602>
> .
>



-- 
@toddmotto

**Comment by ylh23y** [comment]
好

**Comment by toddmotto** [comment]
Closing off, the styleguide has just been completely rewritten in ES6 for Angular 1.5+ (component architecture/components/one-way dataflow etc).
