### ISSUE TITLE
Controllers in Directives?

### ISSUE THREAD

**Issue by raphaelluchini** [toddmotto/angular-styleguide#25]
What you guys think in add something about this topic? I personality like to put all logic of a directive in controllers.. something like that:
```
.directive('myDirective', function(apiService){
    return {
        restrict: 'EA'
        controller: function($scope){
            $scope.fetch = function(){
                return apiService.getData();
            };
        },
        link: function(scope, element, attrs){
            var data = scope.fetch().then(function(){
                element.text(data);
            });
        }
    }
})
```

It's a good practice?

Thanks

**Comment by toddmotto** [comment]
Closing off, the styleguide has just been completely rewritten in ES6 for Angular 1.5+ (component architecture/components/one-way dataflow etc).
