### ISSUE TITLE
Why so specific in naming Services?

### ISSUE THREAD

**Issue by dusbuss** [toddmotto/angular-styleguide#26]
I've been living by this style guide for awhile now, and it's fantastic.

The Service naming is irritating, though.  I'd suggest a more generic name for the Service object inside each service.  Example:
```
function AnotherService () {
  var AnotherService = {};
  /* ... */
  return AnotherService;
}
```
could become... 
```
function AnotherService () {
  var Service = {};
  /* ... */
  return Service;
}
```

There are ~~two~~ three reasons why:
1. jsHint throws irritating "already defined" notices when the internal object is the same name.  
2. It makes it easier to rename services or repurpose snippets in other service.
3. It's more consistent with the way that you're naming controller objects (always with "vm").

I'd love your thoughts on this.  If there's a good reason, I'd like to know and avoid any issues.

Thank you!
Dustin

**Comment by toddmotto** [comment]
Closing off, the styleguide has just been completely rewritten in ES6 for Angular 1.5+ (component architecture/components/one-way dataflow etc).
