### ISSUE TITLE
Controller-as and "this"

### ISSUE THREAD

**Issue by Josh68** [toddmotto/angular-styleguide#27]
Not sure if I'm missing something here, but you first recommend using Controller-as syntax, referencing "this" in the controller for model properties and methods. Then, further on, you recommend setting "this" to "vm" (for ViewModel). Should this just be one recommendation, using Controller-as syntax and assigning "this" to a variable in the context of the controller?

Thanks

**Comment by nazrhyn** [comment]
I'm a little late to the party, but I will echo what @Josh68 was saying (which then got somewhat derailed): I think the first example under **Controllers** shouldn't start with the `this` syntax. Perhaps: reduce the number of code blocks by combination and keep the informative lines about `this` being the same as `$scope` within controllers.

I was somewhat jarred by this in my first reading. I don't remember @johnpapa's guide having the same progression discontinuity. Maybe it does, and my memory of it is just too rosy.

**Comment by toddmotto** [comment]
Closing off, the styleguide has just been completely rewritten in ES6 for Angular 1.5+ (component architecture/components/one-way dataflow etc).

**Comment by Josh68** [comment]
Big thanks for this update, Todd. Cheers

**Comment by toddmotto** [comment]
Cheers Josh :)
