### ISSUE TITLE
Consider recommending new ES6/Traceur friendly ngAnnotate syntax

### ISSUE THREAD

**Issue by jimthedev** [toddmotto/angular-styleguide#29]
For forward compatibility with ES6 would you consider changing your recommendation for ngAnnotate syntax to use the `"ngInject";` directive instead of the comment version of the syntax? 

This is available in the latest version of ngAnnotate and discussed more here: https://github.com/olov/ng-annotate/issues/132

**Comment by toddmotto** [comment]
PR welcome!

**Comment by toddmotto** [comment]
Closing off, the styleguide has just been completely rewritten in ES6 for Angular 1.5+ (component architecture/components/one-way dataflow etc).
