### ISSUE TITLE
What about file organization ?

### ISSUE THREAD

**Issue by ZeBigDuck** [toddmotto/angular-styleguide#39]
I just discovered your styleguide, and it looks awesome ! I can't to use it.

But, I think a chapter about file organization would be nice.

I just saw this : https://github.com/andyjessop/angular-starter#file-structure

But I'm not sure this is the organization I want : in this example, if I have a user registration and a user profile stuff, this would be two different modules, or I should put many views, controllers, services... in the same folder... this would look messy...

Anyway, what's the best practice for file organisation ?

**Comment by Stephn-R** [comment]
@ZeBigDuck I have always promoted this [Video](https://www.youtube.com/watch?v=UlvCbnKAH3g&list=PLXVuZ_5wXUKOovRk7nAjmX-fT9JBUnluI&index=4) as a very good example of how you can structure your Angular projects

**Comment by ZeBigDuck** [comment]
Yeah! Thank you for this link, great video.

The good thing is that John Papa said the same things as this styleguide for all aspects.

This remains not easy to choose between feature or type to organize folders, and I think I'll mix both :)

Thank you Stephn-R!

Anyway, it could be great to add a chapter for this purpose in the styleguide.

**Comment by Stephn-R** [comment]
That depends @ZeBigDuck. Folder naming practices will always vary from user to user. If anything, we can always direct link the video in the Guide as one possible option. But, as I digress, it is always about the scale of the project and project architecture should always aim to assist with growth and never stunt it.

**Comment by toddmotto** [comment]
Included in the rewritten guide launched just now. Closing this off.
