### ISSUE TITLE
Dependency injection for base controllers on Inheritance

### ISSUE THREAD

**Issue by arg20** [toddmotto/angular-styleguide#44]
The style guide presents this code:

```javascript
function BaseCtrl () {
  this.doSomething = function () {

  };
}
BaseCtrl.prototype.someObject = {};
BaseCtrl.prototype.sharedSomething = function () {

};

AnotherCtrl.prototype = Object.create(BaseCtrl.prototype);

function AnotherCtrl () {
  this.anotherSomething = function () {

  };
}
```

My problem is with this line: `AnotherCtrl.prototype = Object.create(BaseCtrl.prototype);`

See in this case it works because BaseCtrl has no dependencies, but that's hardly the case in most scenarios, so I can't just use Object.create, what do we do then?

**Comment by arg20** [comment]
@toddmotto, any clue on this one?

**Comment by toddmotto** [comment]
Hey @arg20 - sorry, been hella busy over late 2015. So, you could do this:

```js
function BaseCtrl($scope, dep1, dep2) {
  this.foo = function () { // uses dep1/dep2 or whatever };
}

function AnotherCtrl($scope, $controller) {
  
  var inherited = $controller('mozioFormBaseCtrl', {
    $scope: $scope
  });

  angular.extend(this, inherited);

  // use this.foo();

}
```

Does that help in this example :)

**Comment by arg20** [comment]
Ah great! thanks man, that's what I was looking for!
