### ISSUE TITLE
This usage of resolve might lead to bad UX

### ISSUE THREAD

**Issue by dmitriz** [toddmotto/angular-styleguide#45]
The recommendation here does not seem to do what the code-to-avoid does:
https://github.com/toddmotto/angular-styleguide#routing-resolves

The second approach blocks the new route change forcing the user to wait, whereas the first one doesn't.

See this discussion:
https://www.reddit.com/r/angularjs/comments/3xq26r/is_resolve_a_ux_antipattern/cyamrzr

**Comment by toddmotto** [comment]
Closing off, the styleguide has just been completely rewritten in ES6 for Angular 1.5+ (component architecture/components/one-way dataflow etc).
