### ISSUE TITLE
module file naming

### ISSUE THREAD

**Issue by ctaepper** [toddmotto/angular-styleguide#58]
First of all : great styleguide!

We are using a very similar approach for some time now. With one little difference in naming conventions: we call our module file `index.js`. This allows the module to be imported with `import Todo from "./todo";` (instead of `from "./todo/todo")`. Also, everyone knows, index.* would be the *start* of a module directory. Any thoughts?

**Comment by toddmotto** [comment]
Hey! Yes - that's a super suggestion, I've been mulling over this as the only potential change to make. Based on the import syntax being clearer it makes sense IMO, happy to take a PR for changes or will update in the next few days! :)

**Comment by ctaepper** [comment]
closed by #59
