### ISSUE TITLE
Portuguese (Portugal pt-pt) version

### ISSUE THREAD

**Issue by joaogarin** [toddmotto/angular-styleguide#67]
Hello Todd,

I can submit a pt-pt translation if that is interesting. People from Brazil / Portugal and many countries from Africa would probably benefit from this. And since I saw a Spanish version was submitted, why not have it in some more languages?

=)

**Comment by toddmotto** [comment]
That'd be amazing @joaogarin ! Thank you :)

**Comment by joaogarin** [comment]
I think we can close this one!)
