### ISSUE TITLE
Add style guide for unit tests

### ISSUE THREAD

**Issue by sylvain-hamel** [toddmotto/angular-styleguide#7]
Hi guys, this is a very helpful article. It'd be nice to have your thoughts on unit test structure and organisation for each type of Angular components (directives, services, filters, etc).

**Comment by toddmotto** [comment]
Closing off, the styleguide has just been completely rewritten in ES6 for Angular 1.5+ (component architecture/components/one-way dataflow etc). I'm not sure whether unit tests really need to be covered, the Angular documentation is pretty awesome now.
