### ISSUE TITLE
Missing import of AppComponent root component in the guide

### ISSUE THREAD

**Issue by TheCypherFR** [toddmotto/angular-styleguide#70]
It seems that the import of the root component `AppComponent ` is missing in the styleguide ([in this section](https://github.com/toddmotto/angular-styleguide#root-module) in the `app.js` file)

Something like that I think :
```javascript
import AppComponent from './app.component';
```

along with these:
```javascript
import Common from './common/common';
import Components from './components/components';
```

or maybe I missed something ?

**Comment by toddmotto** [comment]
Ah yes - oversight on my part - thanks for the heads up! https://github.com/toddmotto/angular-styleguide/commit/81590cf1442e757eef9fb1d43e5bfbeb749d2056
