### ISSUE TITLE
Spec file

### ISSUE THREAD

**Issue by Couto** [toddmotto/angular-styleguide#73]
Could you give an example of a spec file? 

I'm wondering how do you plan your tests, since it might be a little awkward (at least to me) to mix service tests with controller tests on the same file?

I'm most likely missing something here, but I guess you could give some guidance.
Thanks :)

**Comment by floriangosse** [comment]
I think it depends on the test framework you are using. But take a look onto the test files of [AngularClass/NG6-starter](https://AngularClass/NG6-starter/) project. I used it as an inspiration to structure my spec files.

**Comment by floriangosse** [comment]
Hi @Couto, was the NG6-starter project a help?

**Comment by chrisjlee** [comment]
The link is incorrect. you're missing the .com: https://github.com/AngularClass/NG6-starter

**Comment by floriangosse** [comment]
Oh, sorry. I thought that Github format it correctly. :S

**Comment by Couto** [comment]
@floriangosse Hey! It did indeed. Thanks a lot 👍 

However, as a personal opinion, I don't exactly agree with the approach taken (this is a matter of subjective opinion, I truly believe that's nothing technically wrong);

When testing everything (View, Controllers, Services...) in the same spec file, that tends to result in huge files. I rather have smaller files even if that leads to more files.

Still, I'm not really experienced in angular so I'm always open to ideas, or to know what I might be doing the wrong way!

**Comment by floriangosse** [comment]
Yes, that is correct. The files will become huge.

In my componens I test only the controller most of the time an my services are located at other places and in own modules.

**Comment by Couto** [comment]
I do agree with your approach of having services in other modules, unfortunately for my use case, I have to deal with an already existing application where that separation doesn't exist (at least yet).

Having just a directive + controller inside the module, I can imagine the spec file having acceptable an acceptable size.

**Comment by toddmotto** [comment]
App example now links to my contacts manager app that's full of spec files, closing off this one.
