### ISSUE TITLE
any example source?

### ISSUE THREAD

**Issue by atian25** [toddmotto/angular-styleguide#75]
great article, thanks

**Comment by tech-no-logical** [comment]
I've translated the guide into this small plunk. it's not fully functional, but you can get some feel for it at least : 

http://plnkr.co/edit/wGDoJe

**Comment by chihab** [comment]
Here is a sample app following the Styleguide: https://github.com/chihab/angular-styleguide-sample
@toddmotto could take a look at it and add maybe add it to Resources section of Ok.

The sample app is for learning purpose, a more eye friendly version is under development.

The app uses webpack for building and running the app and has the exact same code as in the article.
