### ISSUE TITLE
routed component

### ISSUE THREAD

**Issue by lionelB** [toddmotto/angular-styleguide#79]
Hello todd,

thanks for this new version of your styleguide. You mention in  [routed component](https://github.com/toddmotto/angular-styleguide#routed-components) that we can use a `component` prop when declaring a state but I can't find any documentation in ui-router about  it
```js
    $stateProvider
      .state('todos', {
        url: '/todos',
        component: 'todo',
        resolve: {
          todoData: TodoService => TodoService.getTodos();
        }
      });
  })
```
I like the idea a lot can you have any infos on that ?

**Comment by qlonik** [comment]
Hello. This feature is available in ui-router v1-alpha. It is not present in the current version of ui-router.

**Comment by floriangosse** [comment]
Checkout the issue angular-ui/ui-router#2547. There is a polyfill for it: [ui-router-route-to-components](https://github.com/softsimon/ui-router-route-to-components).

**Comment by floriangosse** [comment]
Hi @lionelB, do you have any further questions?

**Comment by lionelB** [comment]
It' son thanks.

**Comment by toddmotto** [comment]
And now in 1.0.0-beta ui-router :)
