### ISSUE TITLE
[question] EventEmitter

### ISSUE THREAD

**Issue by samithaf** [toddmotto/angular-styleguide#82]
Just wondering which library you are using for EventEmitter.

**Comment by floriangosse** [comment]
Look onto the example of [Stateless components](https://github.com/toddmotto/angular-styleguide#stateless-components). There you can see the registration of a value `EventEmitter` at the bottom. The function returns an object with the property `$event` which contains the passed value.

**Comment by samithaf** [comment]
@floriangosse cheers mate. I haven't noticed it. Was wondering todd might have ported Angular 2 EventEmitter to Angular 1.x
