### ISSUE TITLE
recommend generator 

### ISSUE THREAD

**Issue by colinshen** [toddmotto/angular-styleguide#84]
thanks for your awesome work. but I think if you add some generators/ boilerplates, it would be better. There are some boilerplates, but its hard to find which one is good.

**Comment by samithaf** [comment]
I have been using CLI in https://github.com/AngularClass/NG6-starter last few months and it's pretty good. You will find that project structure is even almost identical. NG6 starter is there for almost 6 months now

**Comment by colinshen** [comment]
yeah, im using this one too. what I meant was put NG6-starter and other generators in your [tools list](https://github.com/toddmotto/angular-styleguide#es2015-and-tooling) to let more people know, and help them build their project.

**Comment by toddmotto** [comment]
Would recommend the NG6 starter also. :)
